
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:1000}
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bomscheduler?useSSL=false
    username: root
    password: root
    hikari:
      connectionTimeout: 3000
      max-lifetime: 58000  # 58s
      maximumPoolSize: 10
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 60000
      auto-commit: false

bomscheduler.processor.mode: "on"
